"""empty message

Revision ID: 3874992394ff
Revises: 
Create Date: 2025-07-23 13:48:30.619918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3874992394ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=True)
    op.create_table('users',
    sa.Column('role', sa.Enum('ADMIN', 'STUDENT', 'TEACHER', 'GUEST', name='role'), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('hast_salt', sa.String(length=500), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('students',
    sa.Column('matric_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matric_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('enrollments',
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('course_id', sa.CHAR(length=36), nullable=False),
    sa.Column('date_enrolled', sa.DateTime(), nullable=False),
    sa.Column('session_semester', sa.String(length=20), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('enrollment_id', sa.CHAR(length=36), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessments')
    op.drop_table('enrollments')
    op.drop_table('students')
    op.drop_table('users')
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
