"""empty message

Revision ID: ea4ea17694b0
Revises: ff778b1621dd
Create Date: 2025-07-23 17:32:53.666149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea4ea17694b0'
down_revision: Union[str, Sequence[str], None] = 'ff778b1621dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_salt', sa.String(length=500), nullable=False))
    op.drop_column('users', 'hast_salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hast_salt', mysql.VARCHAR(length=500), nullable=False))
    op.drop_column('users', 'hash_salt')
    # ### end Alembic commands ###
